#!/bin/bash

cd `dirname $BASH_SOURCE`

echo -e "\n\n_______ GrubbyDatabaseTest _______"
phpunit GrubbyDatabaseTest.php

echo -e "\n\n_______ GrubbyTest _______"
phpunit GrubbyTest.php

echo -e "\n\n_______ GrubbyDatabaseTest using config-db.php _______"
phpunit --bootstrap config-db.php GrubbyDatabaseTest.php
