#!/bin/bash

cd `dirname $BASH_SOURCE`

echo -e "\n_____GrubbyDatabaseTest_____________________________________________"
phpunit GrubbyDatabaseTest.php

echo -e "\n_____GrubbyTest_____________________________________________________"
phpunit GrubbyTest.php

echo -e "\n_____GrubbyDatabaseTest using config-db.php_________________________"
phpunit --bootstrap config-db.php GrubbyDatabaseTest.php
